CREATE TABLE "postoffice_question" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "question_text" varchar(200) NOT NULL, "pub_date" timestamp with time zone NOT NULL);
CREATE TABLE "postoffice_choice" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "question_id" bigint NOT NULL, "choice_text" varchar(200) NOT NULL, "votes" integer NOT NULL);
ALTER TABLE "postoffice_choice" ADD CONSTRAINT "postoffice_choice_question_id_50d0bcf7_fk_postoffic" FOREIGN KEY ("question_id") REFERENCES "postoffice_question" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "postoffice_choice_question_id_50d0bcf7" ON "postoffice_choice" ("question_id");
